---
title: "R Bootcamp Einstein 2017 Session 2"
author: Michoel Snow
date: August 8 & 10, 2017
output: 
  revealjs::revealjs_presentation:
    center: FALSE
    theme: sky
    transition: concave
    css: r_bootcamp_einstein_2017_revealjs.css
    highlight: tango
    fig_height: 5
    reveal_options:
      width: '100%'
      height: '100%'
      margin: 0.1
---
```{r global_options, include=FALSE, warning=FALSE}
options(width = 120)
knitr::opts_chunk$set(tidy.opts=list(width.cutoff=120),width=120,tidy=TRUE)
```

```{r, echo=FALSE,include=FALSE}
library(tidyverse)
library(NHANES)
library(lubridate)
```


## Example presentations

## NHANES Sex & Drugs {.scrollable}

Correlation does not imply causation!
```{r, tidy =FALSE}
nh_tbl <- as_tibble(NHANES)
nh_tbl_sex <- nh_tbl %>% filter(!is.na(SexOrientation))
nh_tbl_sex %>% ggplot(aes(SexOrientation)) + geom_bar(fill="blue")
nh_tbl_sex %>% ggplot(aes(SexOrientation)) + geom_bar(aes(fill=Gender),position="dodge")
nh_tbl_sex %>% filter(SexOrientation!="Heterosexual") %>% 
  ggplot(aes(SexOrientation,fill=Gender)) + geom_bar(position="dodge")
nh_tbl_sex %>% filter(SexOrientation!="Heterosexual") %>% 
  ggplot(aes(SexOrientation,fill=SameSex)) + geom_bar(position="dodge")
nh_tbl_sex %>% filter(!is.na(SameSex), SexOrientation=="Heterosexual",SameSex == "Yes") %>% 
  ggplot(aes(Gender,fill=Gender)) + geom_bar() + 
  labs(title = "Identify as Heterosexual with Same Sex Experience") +
  theme(plot.title = element_text(hjust = 0.5))
```


```{r, warning=FALSE, tidy=FALSE}
nh_tbl_mj <- nh_tbl %>% filter(!is.na(Marijuana)) 
nh_tbl_mj %>% ggplot(aes(Age,fill=Marijuana)) + geom_bar(position="dodge")
nh_tbl_mj %>% ggplot(aes(Age,fill=RegularMarij)) + geom_bar(position="dodge")
nh_tbl_mj %>% filter(!is.na(HardDrugs)) %>% filter(HardDrugs=="Yes") %>% ggplot(aes(Marijuana)) + geom_bar(fill = "Blue") + 
  labs(title = "Participants who have tried cocaine, crack cocaine, heroin or methamphetamine") +
  theme(plot.title = element_text(hjust = 0.5))
nh_tbl_mj %>% filter(!is.na(HardDrugs)) %>% filter(Marijuana=="Yes") %>% ggplot(aes(HardDrugs)) + geom_bar(fill = "Blue") + 
  labs(title = "Participants who have tried marijuana") +
  theme(plot.title = element_text(hjust = 0.5))

```

## Citibike {.scrollable}

```{r}
column_names <- c('trip_duration','start_time', 'stop_time', 'start_id', 'start_name', 'end_id', 'end_name', 'bike_id', 'user_type', 'birth_year', 'gender')
citi_bike <- read_csv('./data/201701-citibike-tripdata.csv',col_names = column_names, skip=1)
```

```{r}
citi_bike %>% mutate(start_hr = hour(start_time)) %>% 
  ggplot(aes(start_hr)) + geom_histogram(bins=24,fill="blue",color="black")
citi_bike %>% mutate(day_of_week = wday(start_time)) %>% 
  ggplot(aes(day_of_week)) + geom_histogram(bins=7,fill="blue",color="black")
```

```{r}
citi_bike %>% mutate(travel_time = as.double(stop_time-start_time)) %>% 
  ggplot(aes(travel_time)) + geom_histogram(bins=30)
citi_bike %>% mutate(travel_time = as.double(stop_time-start_time)) %>% filter(travel_time<80) %>% 
  ggplot(aes(travel_time)) + geom_histogram(stat = "density")
```

```{r}
citi_bike %>% mutate(travel_time = as.double(stop_time-start_time), start_min = min(start_time)) %>% filter(travel_time<80) %>% 
  ggplot(aes(start_time,travel_time)) + geom_jitter()
```

## 
```{r, eval=FALSE}
brfss <- read_csv('./data/BRFSS.csv')

brfss2 <- brfss[1:1000,]
brfss <- brfss %>% select(-c(POORHLTH,CHECKUP1,CHOLCHK,USENOW3,EXRACT11,EXEROFT1,EXERHMM1,EXRACT21,EXEROFT2,EXERHMM2,STRENGTH,LMTJOIN3,JOINPAIN,FLSHTMY2,IMFVPLAC,HIVTSTD3,WHRTST10,BLDSUGAR, FEETCHK2, FEETCHK, EYEEXAM, DIABEYE, QLMENTL2:QLHLTH2, VIDFCLT2, VIREDIF3, VIPRFVS2))
```

```{r, eval=FALSE}
brfss$CVDINFR4 <- recode(brfss$CVDINFR4,`1`= 'YES',`2` = 'NO', .default = NA_character_)
brfss$HLTHPLN1 <- recode(brfss$HLTHPLN1,`1`= 'YES',`2` = 'NO', .default = NA_character_)
brfss$GENHLTH <- recode(brfss$GENHLTH,`1`= 'EXCELLENT',`2` = 'VERY GOOD', `3` = "GOOD", `4` = "FAIR", `5` = "POOR",.default = NA_character_)
brfss$PHYSHLTH[brfss$PHYSHLTH==77 | brfss$PHYSHLTH==99] <- NA
brfss$PHYSHLTH[brfss$PHYSHLTH==88] <- 0
brfss$PERSDOC2 <- recode(brfss$PERSDOC2,`1`= 'YES',`2` = 'YES', `3` = 'NO', .default = NA_character_)
brfss$MEDCOST <- recode(brfss$MEDCOST,`1`= 'YES',`2` = 'NO', .default = NA_character_)
brfss$BPHIGH4 <- recode(brfss$BPHIGH4,`1`= 'YES',`3` = 'NO', .default = NA_character_)
brfss$BPMEDS <- recode(brfss$BPMEDS,`1`= 'YES',`3` = 'NO', .default = NA_character_)
brfss$BLOODCHO <- recode(brfss$BLOODCHO,`1`= 'YES',`2` = 'NO', .default = NA_character_)
brfss$TOLDHI2 <- recode(brfss$TOLDHI2,`1`= 'YES',`2` = 'NO', .default = NA_character_)
brfss$CVDCRHD4 <- recode(brfss$CVDCRHD4,`1`= 'YES',`2` = 'NO', .default = NA_character_)
brfss$CVDSTRK3 <- recode(brfss$CVDSTRK3,`1`= 'YES',`2` = 'NO', .default = NA_character_)
brfss$ASTHMA3 <- recode(brfss$ASTHMA3,`1`= 'YES',`2` = 'NO', .default = NA_character_)
brfss$ASTHNOW <- recode(brfss$ASTHNOW,`1`= 'YES',`2` = 'NO', .default = NA_character_)
brfss$CHCSCNCR <- recode(brfss$CHCSCNCR,`1`= 'YES',`2` = 'NO', .default = NA_character_)
brfss$CHCOCNCR <- recode(brfss$CHCOCNCR,`1`= 'YES',`2` = 'NO', .default = NA_character_)
brfss$CHCCOPD1 <- recode(brfss$CHCCOPD1,`1`= 'YES',`2` = 'NO', .default = NA_character_)
brfss$HAVARTH3 <- recode(brfss$HAVARTH3,`1`= 'YES',`2` = 'NO', .default = NA_character_)
brfss$ADDEPEV2 <- recode(brfss$ADDEPEV2,`1`= 'YES',`2` = 'NO', .default = NA_character_)
brfss$CHCKIDNY <- recode(brfss$CHCKIDNY,`1`= 'YES',`2` = 'NO', .default = NA_character_)
brfss$DIABETE3 <- recode(brfss$DIABETE3,`1`= 'YES',`3` = 'NO', .default = NA_character_)
brfss$DIABAGE2[brfss$DIABAGE2>=98] <- NA
brfss$SEX <- recode(brfss$SEX,`1`= 'MALE',`2` = 'FEMALE', .default = NA_character_)
brfss$MARITAL <- recode(brfss$MARITAL,`1`= 'MARRIED',`2` = 'DIVORCED', `3` = 'WIDOWED', `4` = 'SEPARATED', `5` = 'NEVER MARRIED', `6` = 'UNMARRIED COUPLE', .default = NA_character_)
brfss$EDUCA <- recode(brfss$EDUCA,`1`= 'NO SCHOOL',`2` = 'ELEMENTARY', `3`='SOME HIGH SCHOOL',`4`='HIGH SCHOOL',`5`= 'SOME COLLEGE', `6` = 'COLLEGE', .default = NA_character_)
brfss$VETERAN3 <- recode(brfss$VETERAN3,`1`= 'YES',`2` = 'NO', .default = NA_character_)
brfss$EMPLOY1 <- recode(brfss$EMPLOY1,`1`= 'YES',`2` = 'YES', `3`='NO', `4` = 'NO', `5`='HOMEMAKER', `6`='STUDENT', `7` = 'RETIRED', .default = NA_character_)
brfss$CHILDREN[brfss$CHILDREN==99] <- NA
brfss$CHILDREN[brfss$CHILDREN==88] <- 0
brfss$INCOME2 <- recode(brfss$INCOME2,`1`= 'LESS THAN 10,000',`2` = 'LESS THAN 15,000',`3` = 'LESS THAN 20,000', `4` = 'LESS THAN 25,000', `5` = 'LESS THAN 35,000', `6` = 'LESS THAN 50,000', `7` = 'LESS THAN 75,000', `8` = '75,000 OR MORE', .default = NA_character_)
brfss$WEIGHT2[brfss$WEIGHT2>=9999] <- NA
brfss$WEIGHT2[brfss$WEIGHT2>=9000 & !is.na(brfss$WEIGHT2)] <- (brfss$WEIGHT2[brfss$WEIGHT2>=9000 & !is.na(brfss$WEIGHT2)]-9000) * 2.2
brfss$WEIGHT2[brfss$WEIGHT2>=1000] <- NA

brfss$HEIGHT3[brfss$HEIGHT3<200] <-  NA
brfss$HEIGHT3[brfss$HEIGHT3>=200 & brfss$HEIGHT3<=711 & !is.na(brfss$HEIGHT3)] <- brfss$HEIGHT3[brfss$HEIGHT3>=200 & brfss$HEIGHT3<=711 & !is.na(brfss$HEIGHT3)] %/% 100 * 12 * 2.54 + brfss$HEIGHT3[brfss$HEIGHT3>=200 & brfss$HEIGHT3<=711 & !is.na(brfss$HEIGHT3)] %% 100 * 2.54
brfss$HEIGHT3[brfss$HEIGHT3>=9000 & brfss$HEIGHT3<=9998 & !is.na(brfss$HEIGHT3)] <- 
  brfss$HEIGHT3[brfss$HEIGHT3>=9000 & brfss$HEIGHT3<=9998 & !is.na(brfss$HEIGHT3)] - 9000
brfss$HEIGHT3[brfss$HEIGHT3>=1000] <-  NA

brfss$PREGNANT <- recode(brfss$PREGNANT,`1`= 'YES',`2` = 'NO', .default = NA_character_)
brfss$QLACTLM2 <- recode(brfss$QLACTLM2,`1`= 'YES',`2` = 'NO', .default = NA_character_)
brfss$USEEQUIP <- recode(brfss$USEEQUIP,`1`= 'YES',`2` = 'NO', .default = NA_character_)
brfss$BLIND <- recode(brfss$BLIND,`1`= 'YES',`2` = 'NO', .default = NA_character_)
brfss$DIFFALON <- recode(brfss$DIFFALON,`1`= 'YES',`2` = 'NO', .default = NA_character_)
brfss$SMOKE100 <- recode(brfss$SMOKE100,`1`= 'YES',`2` = 'NO', .default = NA_character_)
brfss$SMOKDAY2 <- recode(brfss$SMOKDAY2,`1`= 'EVERY DAY',`2` = 'SOME DAYS', `3` = 'NOT AT ALL', .default = NA_character_)
brfss$STOPSMK2 <- recode(brfss$STOPSMK2,`1`= 'YES',`2` = 'NO', .default = NA_character_)
brfss$LASTSMK2 <- recode(brfss$LASTSMK2,`1`= 'LESS THAN 1 MONTH',`2` = '1 TO 3 MONTHS', `3` = '3 TO 6 MONTHS', `4` = '6 TO 12 MONTHS', `5` = '1 TO 5 YEARS', `6` = '5 TO 10 YEARS', `7` = '10 YEARS OR MORE', `8` = 'NEVER SMOKED REGULARLY', .default = NA_character_)

brfss$ALCDAY5[brfss$ALCDAY5 > 100 & brfss$ALCDAY5< 200 & !is.na(brfss$ALCDAY5)] <- 
  (brfss$ALCDAY5[brfss$ALCDAY5 > 100 & brfss$ALCDAY5< 200 & !is.na(brfss$ALCDAY5)]- 100)*30/7
brfss$ALCDAY5[brfss$ALCDAY5 > 200 & brfss$ALCDAY5< 300 & !is.na(brfss$ALCDAY5)] <- 
  brfss$ALCDAY5[brfss$ALCDAY5 > 200 & brfss$ALCDAY5< 300 & !is.na(brfss$ALCDAY5)]- 200
brfss$ALCDAY5[brfss$ALCDAY5 > 300] <- NA
brfss$ALCDAY5 <- brfss$ALCDAY5%/%1

brfss$AVEDRNK2[brfss$AVEDRNK2 == 88 & !is.na(brfss$AVEDRNK2)] <- 0
brfss$AVEDRNK2[brfss$AVEDRNK2 > 76] <- NA

brfss$DRNK3GE5[brfss$DRNK3GE5 == 88 & !is.na(brfss$DRNK3GE5)] <- 0
brfss$DRNK3GE5[brfss$DRNK3GE5 > 76] <- NA

brfss$MAXDRNKS[brfss$MAXDRNKS > 76] <- NA

brfss$FRUITJU1[brfss$FRUITJU1 > 100 & brfss$FRUITJU1< 200 & !is.na(brfss$FRUITJU1)] <- 
  (brfss$FRUITJU1[brfss$FRUITJU1 > 100 & brfss$FRUITJU1< 200 & !is.na(brfss$FRUITJU1)]- 100)*30
brfss$FRUITJU1[brfss$FRUITJU1 > 200 & brfss$FRUITJU1< 300 & !is.na(brfss$FRUITJU1)] <- 
  (brfss$FRUITJU1[brfss$FRUITJU1 > 200 & brfss$FRUITJU1< 300 & !is.na(brfss$FRUITJU1)]- 200)*30/7
brfss$FRUITJU1[brfss$FRUITJU1 > 300 & brfss$FRUITJU1< 400 & !is.na(brfss$FRUITJU1)] <- 
  brfss$FRUITJU1[brfss$FRUITJU1 > 300 & brfss$FRUITJU1< 400 & !is.na(brfss$FRUITJU1)]- 300
brfss$FRUITJU1[(brfss$FRUITJU1 == 300 | brfss$FRUITJU1 == 555) & is.na(brfss$FRUITJU1)] <- 0
brfss$FRUITJU1[brfss$FRUITJU1 > 300] <- NA
brfss$FRUITJU1 <- brfss$FRUITJU1%/%1


brfss$FRUIT1[brfss$FRUIT1 > 100 & brfss$FRUIT1< 200 & !is.na(brfss$FRUIT1)] <- 
  (brfss$FRUIT1[brfss$FRUIT1 > 100 & brfss$FRUIT1< 200 & !is.na(brfss$FRUIT1)]- 100)*30
brfss$FRUIT1[brfss$FRUIT1 > 200 & brfss$FRUIT1< 300 & !is.na(brfss$FRUIT1)] <- 
  (brfss$FRUIT1[brfss$FRUIT1 > 200 & brfss$FRUIT1< 300 & !is.na(brfss$FRUIT1)]- 200)*30/7
brfss$FRUIT1[brfss$FRUIT1 > 300 & brfss$FRUIT1< 400 & !is.na(brfss$FRUIT1)] <- 
  brfss$FRUIT1[brfss$FRUIT1 > 300 & brfss$FRUIT1< 400 & !is.na(brfss$FRUIT1)]- 300
brfss$FRUIT1[(brfss$FRUIT1 == 300 | brfss$FRUIT1 == 555) & is.na(brfss$FRUIT1)] <- 0
brfss$FRUIT1[brfss$FRUIT1 > 300] <- NA
brfss$FRUIT1 <- brfss$FRUIT1%/%1

brfss$FVBEANS[brfss$FVBEANS > 100 & brfss$FVBEANS< 200 & !is.na(brfss$FVBEANS)] <- 
  (brfss$FVBEANS[brfss$FVBEANS > 100 & brfss$FVBEANS< 200 & !is.na(brfss$FVBEANS)]- 100)*30
brfss$FVBEANS[brfss$FVBEANS > 200 & brfss$FVBEANS< 300 & !is.na(brfss$FVBEANS)] <- 
  (brfss$FVBEANS[brfss$FVBEANS > 200 & brfss$FVBEANS< 300 & !is.na(brfss$FVBEANS)]- 200)*30/7
brfss$FVBEANS[brfss$FVBEANS > 300 & brfss$FVBEANS< 400 & !is.na(brfss$FVBEANS)] <- 
  brfss$FVBEANS[brfss$FVBEANS > 300 & brfss$FVBEANS< 400 & !is.na(brfss$FVBEANS)]- 300
brfss$FVBEANS[(brfss$FVBEANS == 300 | brfss$FVBEANS == 555) & is.na(brfss$FVBEANS)] <- 0
brfss$FVBEANS[brfss$FVBEANS > 300] <- NA
brfss$FVBEANS <- brfss$FVBEANS%/%1



brfss$FVGREEN[brfss$FVGREEN > 100 & brfss$FVGREEN< 200 & !is.na(brfss$FVGREEN)] <- 
  (brfss$FVGREEN[brfss$FVGREEN > 100 & brfss$FVGREEN< 200 & !is.na(brfss$FVGREEN)]- 100)*30
brfss$FVGREEN[brfss$FVGREEN > 200 & brfss$FVGREEN< 300 & !is.na(brfss$FVGREEN)] <- 
  (brfss$FVGREEN[brfss$FVGREEN > 200 & brfss$FVGREEN< 300 & !is.na(brfss$FVGREEN)]- 200)*30/7
brfss$FVGREEN[brfss$FVGREEN > 300 & brfss$FVGREEN< 400 & !is.na(brfss$FVGREEN)] <- 
  brfss$FVGREEN[brfss$FVGREEN > 300 & brfss$FVGREEN< 400 & !is.na(brfss$FVGREEN)]- 300
brfss$FVGREEN[(brfss$FVGREEN == 300 | brfss$FVGREEN == 555) & is.na(brfss$FVGREEN)] <- 0
brfss$FVGREEN[brfss$FVGREEN > 300] <- NA
brfss$FVGREEN <- brfss$FVGREEN%/%1


brfss$FVORANG[brfss$FVORANG > 100 & brfss$FVORANG< 200 & !is.na(brfss$FVORANG)] <- 
  (brfss$FVORANG[brfss$FVORANG > 100 & brfss$FVORANG< 200 & !is.na(brfss$FVORANG)]- 100)*30
brfss$FVORANG[brfss$FVORANG > 200 & brfss$FVORANG< 300 & !is.na(brfss$FVORANG)] <- 
  (brfss$FVORANG[brfss$FVORANG > 200 & brfss$FVORANG< 300 & !is.na(brfss$FVORANG)]- 200)*30/7
brfss$FVORANG[brfss$FVORANG > 300 & brfss$FVORANG< 400 & !is.na(brfss$FVORANG)] <- 
  brfss$FVORANG[brfss$FVORANG > 300 & brfss$FVORANG< 400 & !is.na(brfss$FVORANG)]- 300
brfss$FVORANG[(brfss$FVORANG == 300 | brfss$FVORANG == 555) & is.na(brfss$FVORANG)] <- 0
brfss$FVORANG[brfss$FVORANG > 300] <- NA
brfss$FVORANG <- brfss$FVORANG%/%1

brfss$VEGETAB1[brfss$VEGETAB1 > 100 & brfss$VEGETAB1< 200 & !is.na(brfss$VEGETAB1)] <- 
  (brfss$VEGETAB1[brfss$VEGETAB1 > 100 & brfss$VEGETAB1< 200 & !is.na(brfss$VEGETAB1)]- 100)*30
brfss$VEGETAB1[brfss$VEGETAB1 > 200 & brfss$VEGETAB1< 300 & !is.na(brfss$VEGETAB1)] <- 
  (brfss$VEGETAB1[brfss$VEGETAB1 > 200 & brfss$VEGETAB1< 300 & !is.na(brfss$VEGETAB1)]- 200)*30/7
brfss$VEGETAB1[brfss$VEGETAB1 > 300 & brfss$VEGETAB1< 400 & !is.na(brfss$VEGETAB1)] <- 
  brfss$VEGETAB1[brfss$VEGETAB1 > 300 & brfss$VEGETAB1< 400 & !is.na(brfss$VEGETAB1)]- 300
brfss$VEGETAB1[(brfss$VEGETAB1 == 300 | brfss$VEGETAB1 == 555) & is.na(brfss$VEGETAB1)] <- 0
brfss$VEGETAB1[brfss$VEGETAB1 > 300] <- NA
brfss$VEGETAB1 <- brfss$VEGETAB1%/%1

brfss$EXERANY2 <- recode(brfss$EXERANY2,`1`= 'YES',`2` = 'NO', .default = NA_character_)
brfss$SEATBELT <- recode(brfss$SEATBELT,`1`= 'ALWAYS',`2` = 'NEARLY ALWAYS', `3` = "SOMETIMES", `4` = "SELDOM", `5` = "NEVER",.default = NA_character_)


brfss$FLUSHOT6 <- recode(brfss$FLUSHOT6,`1`= 'YES',`2` = 'NO', .default = NA_character_)
brfss$PNEUVAC3 <- recode(brfss$PNEUVAC3,`1`= 'YES',`2` = 'NO', .default = NA_character_)
brfss$HIVTST6 <- recode(brfss$HIVTST6,`1`= 'YES',`2` = 'NO', .default = NA_character_)
brfss$PDIABTST <- recode(brfss$PDIABTST,`1`= 'YES',`2` = 'NO', .default = NA_character_)
brfss$PREDIAB1 <- recode(brfss$PREDIAB1,`1`= 'YES',`3` = 'NO', .default = NA_character_)
brfss$INSULIN <- recode(brfss$INSULIN,`1`= 'YES',`2` = 'NO', .default = NA_character_)

brfss$DOCTDIAB[brfss$DOCTDIAB == 88 & !is.na(brfss$DOCTDIAB)] <- 0
brfss$DOCTDIAB[brfss$DOCTDIAB > 76] <- NA

brfss$CHKHEMO3[brfss$CHKHEMO3 == 88 & !is.na(brfss$CHKHEMO3)] <- 0
brfss$CHKHEMO3[brfss$CHKHEMO3 > 76] <- NA

brfss$INSULIN <- recode(brfss$INSULIN,`1`= 'YES',`2` = 'NO', .default = NA_character_)
brfss$INSULIN <- recode(brfss$INSULIN,`1`= 'YES',`2` = 'NO', .default = NA_character_)
brfss$INSULIN <- recode(brfss$INSULIN,`1`= 'YES',`2` = 'NO', .default = NA_character_)
brfss$INSULIN <- recode(brfss$INSULIN,`1`= 'YES',`2` = 'NO', .default = NA_character_)
brfss$INSULIN <- recode(brfss$INSULIN,`1`= 'YES',`2` = 'NO', .default = NA_character_)
brfss$INSULIN <- recode(brfss$INSULIN,`1`= 'YES',`2` = 'NO', .default = NA_character_)
brfss$INSULIN <- recode(brfss$INSULIN,`1`= 'YES',`2` = 'NO', .default = NA_character_)
brfss$INSULIN <- recode(brfss$INSULIN,`1`= 'YES',`2` = 'NO', .default = NA_character_)
brfss$INSULIN <- recode(brfss$INSULIN,`1`= 'YES',`2` = 'NO', .default = NA_character_)
brfss$INSULIN <- recode(brfss$INSULIN,`1`= 'YES',`2` = 'NO', .default = NA_character_)


brfss <- brfss %>% rename(STATE=`_STATE`,WEIGHT2_LB = WEIGHT2, HEIGHT_CM = HEIGHT3)
```


```{r}
brfss %>% filter(CVDINFR4==1) %>% group_by(STATE) %>% summarise(MI = sum(CVDINFR4), count = n()) %>% ggplot(aes(STATE,MI)) +
  geom_point()

```


```{r}
brfss %>% filter(!is.na(HLTHPLN1),!is.na(CVDINFR4)) %>% ggplot(aes(HLTHPLN1)) + 
  geom_bar(aes(fill=CVDINFR4),position = "dodge")
brfss %>% filter(!is.na(HLTHPLN1),!is.na(CVDINFR4)) %>% ggplot(aes(CVDINFR4,fill=HLTHPLN1)) + 
  geom_bar(position = "dodge")

```


<!-- aa <- read_xpt('./data/LLCP2015.XPT') -->
<!-- cc <- as_tibble(aa) -->
<!-- cc <- cc %>% select(-c(SEQNO,`_PSU`)) -->
<!-- cc <- cc %>% select(-c(DISPCODE,IDATE,CTELENUM,PVTRESD1,COLGHOUS,STATERES,CELLFON3,CTELNUM1,CELLFON2,LANDLINE,CSTATE,PVTRESD2,CCLGHOUS,RENTHOM1,NUMHHOL2,NUMPHON2,CPDEMO1,INTERNET,ARTHDIS2,ARTHSOCL,DIABEDU,PAINACT2,CAREGIV1,CRGVREL1,CRGVLNG1,CRGVHRS1,CRGVPRB1,CRGVPERS,CRGVHOUS,CRGVMST2,CRGVEXPT,SCNTMNY1,SCNTMEL1,SCNTPAID,SCNTLPAD,EMTSUPRT,LSATISFY,QSTVER,EXACTOT1,EXACTOT2,MSCODE,`_STSTR`,`_STRWT`,`_RAWRAKE`,`_WT2RAKE`,`_CLLCPWT`,`_DUALUSE`,`_DUALCOR`,`_LLCPWT`,`_RFHLTH`,`_HCVU651`,`_RFHYPE5`,`_CHOLCHK`,`_RFCHOL`,`_MICHD`,`_LTASTH1`:`_AIDTST3`)) -->
<!-- write_csv(cc,'./data/BRFSS.csv') -->